--- 
:system: 
- actionwebservice
- acts_as_ferret
- cgi_multipart_eof_fix
- daemons
- dnssd
- fastthread
- fcgi
- ferret
- gem_plugin
- libxml-ruby
- needle
- net-sftp
- net-ssh
- rubynode
- ruby-openid
- ruby-yadis
- termios
:exception: 
- tlsmail
- rubygems-update
:github: 
- adamwiggins-rest-client
- collectiveidea-awesome_nested_set
- jeremymcanally-pending
- mbleigh-acts-as-taggable-on
- mynyml-every
- n3bulous-amiruby19
:approved: 
- activerecord
- activesupport
- adamwiggins-rest-client
- andand
- capistrano
- cheat
- cldwalker-alias
- cldwalker-console_update
- cldwalker-core
- cldwalker-has_machine_tags
- cldwalker-hirb
- collectiveidea-awesome_nested_set
- dcadenas-gmail_sender
- defunkt-github
- duration
- gem_grep
- googlereader
- grancher
- highline
- hpricot
- httparty
- jeremymcanally-context
- jeremymcanally-matchy
- jeremymcanally-pending
- jeremymcanally-stump
- levenshtein
- lightning
- local_gem
- matthew-method_lister
- mbleigh-acts-as-taggable-on
- mislav-hanna
- mislav-will_paginate
- mocha
- mojombo-jekyll
- mongrel
- mynyml-every
- mysql
- n3bulous-amiruby19
- nokogiri
- ParseTree
- rack
- rails
- rake
- rcov
- rdoc
- RedCloth
- rip
- rr
- rspec
- rspec-rails
- rubish
- ruby-debug
- ruby2ruby
- rubyforge
- rubypan
- sinatra
- sketches
- sqlite3-ruby
- ssoroka-ansi
- stephencelis-ghi
- tabtab
- technicalpickles-jeweler
- thor
- unroller
- webmat-git_remote_branch
- what_methods
- wirble
- www-delicious
- Platform
- mspec
- bond
- hirb
- rvm
- boson
- test-unit
- file-find
- timocratic-test_benchmark
- twitter
